Repository Meliox/PVE-mods, pull requests merged in 2024-06, with the labels that each got.

#47 Add system information #2
  pve-mod-gui-sensors.sh
Labels: enhancement

#50 Add "remote" debug option of json file
  pve-mod-gui-sensors.sh
Labels: enhancement

#49 Add support for multiple AMD temp types
  pve-mod-gui-sensors.sh
Labels: bug

#54 Option to display Intel package temp or cores
  pve-mod-gui-sensors.sh
Labels: enhancement

#42 add support multiple Fan Speed Key Patterns
  pve-mod-gui-sensors.sh
Labels: bug, enhancement

#57 Color prompts
  pve-mod-gui-sensors.sh
Labels: enhancement
